//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
// 
#pragma warning disable 1591

namespace Lib.Form {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TransferFormWSSoap", Namespace="http://www.1st-excellence.com")]
    public partial class TransferFormWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendFormOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFormListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetExternalFormListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFormStructureOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFormStructureByFormIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTaskDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetRelayFormDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback TerminateTaskOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTaskResultOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TransferFormWS() {
            this.Url = global::Lib.Properties.Settings.Default.Lib_Form_TransferFormWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendFormCompletedEventHandler SendFormCompleted;
        
        /// <remarks/>
        public event GetFormListCompletedEventHandler GetFormListCompleted;
        
        /// <remarks/>
        public event GetExternalFormListCompletedEventHandler GetExternalFormListCompleted;
        
        /// <remarks/>
        public event GetFormStructureCompletedEventHandler GetFormStructureCompleted;
        
        /// <remarks/>
        public event GetFormStructureByFormIdCompletedEventHandler GetFormStructureByFormIdCompleted;
        
        /// <remarks/>
        public event GetTaskDataCompletedEventHandler GetTaskDataCompleted;
        
        /// <remarks/>
        public event SetRelayFormDataCompletedEventHandler SetRelayFormDataCompleted;
        
        /// <remarks/>
        public event TerminateTaskCompletedEventHandler TerminateTaskCompleted;
        
        /// <remarks/>
        public event GetTaskResultCompletedEventHandler GetTaskResultCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.1st-excellence.com/SendForm", RequestNamespace="http://www.1st-excellence.com", ResponseNamespace="http://www.1st-excellence.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendForm(string xmlFormInfo) {
            object[] results = this.Invoke("SendForm", new object[] {
                        xmlFormInfo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendFormAsync(string xmlFormInfo) {
            this.SendFormAsync(xmlFormInfo, null);
        }
        
        /// <remarks/>
        public void SendFormAsync(string xmlFormInfo, object userState) {
            if ((this.SendFormOperationCompleted == null)) {
                this.SendFormOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendFormOperationCompleted);
            }
            this.InvokeAsync("SendForm", new object[] {
                        xmlFormInfo}, this.SendFormOperationCompleted, userState);
        }
        
        private void OnSendFormOperationCompleted(object arg) {
            if ((this.SendFormCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendFormCompleted(this, new SendFormCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.1st-excellence.com/GetFormList", RequestNamespace="http://www.1st-excellence.com", ResponseNamespace="http://www.1st-excellence.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetFormList() {
            object[] results = this.Invoke("GetFormList", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFormListAsync() {
            this.GetFormListAsync(null);
        }
        
        /// <remarks/>
        public void GetFormListAsync(object userState) {
            if ((this.GetFormListOperationCompleted == null)) {
                this.GetFormListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFormListOperationCompleted);
            }
            this.InvokeAsync("GetFormList", new object[0], this.GetFormListOperationCompleted, userState);
        }
        
        private void OnGetFormListOperationCompleted(object arg) {
            if ((this.GetFormListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFormListCompleted(this, new GetFormListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.1st-excellence.com/GetExternalFormList", RequestNamespace="http://www.1st-excellence.com", ResponseNamespace="http://www.1st-excellence.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetExternalFormList() {
            object[] results = this.Invoke("GetExternalFormList", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetExternalFormListAsync() {
            this.GetExternalFormListAsync(null);
        }
        
        /// <remarks/>
        public void GetExternalFormListAsync(object userState) {
            if ((this.GetExternalFormListOperationCompleted == null)) {
                this.GetExternalFormListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetExternalFormListOperationCompleted);
            }
            this.InvokeAsync("GetExternalFormList", new object[0], this.GetExternalFormListOperationCompleted, userState);
        }
        
        private void OnGetExternalFormListOperationCompleted(object arg) {
            if ((this.GetExternalFormListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetExternalFormListCompleted(this, new GetExternalFormListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.1st-excellence.com/GetFormStructure", RequestNamespace="http://www.1st-excellence.com", ResponseNamespace="http://www.1st-excellence.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetFormStructure(string formVersionId) {
            object[] results = this.Invoke("GetFormStructure", new object[] {
                        formVersionId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFormStructureAsync(string formVersionId) {
            this.GetFormStructureAsync(formVersionId, null);
        }
        
        /// <remarks/>
        public void GetFormStructureAsync(string formVersionId, object userState) {
            if ((this.GetFormStructureOperationCompleted == null)) {
                this.GetFormStructureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFormStructureOperationCompleted);
            }
            this.InvokeAsync("GetFormStructure", new object[] {
                        formVersionId}, this.GetFormStructureOperationCompleted, userState);
        }
        
        private void OnGetFormStructureOperationCompleted(object arg) {
            if ((this.GetFormStructureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFormStructureCompleted(this, new GetFormStructureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.1st-excellence.com/GetFormStructureByFormId", RequestNamespace="http://www.1st-excellence.com", ResponseNamespace="http://www.1st-excellence.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetFormStructureByFormId(string formId) {
            object[] results = this.Invoke("GetFormStructureByFormId", new object[] {
                        formId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFormStructureByFormIdAsync(string formId) {
            this.GetFormStructureByFormIdAsync(formId, null);
        }
        
        /// <remarks/>
        public void GetFormStructureByFormIdAsync(string formId, object userState) {
            if ((this.GetFormStructureByFormIdOperationCompleted == null)) {
                this.GetFormStructureByFormIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFormStructureByFormIdOperationCompleted);
            }
            this.InvokeAsync("GetFormStructureByFormId", new object[] {
                        formId}, this.GetFormStructureByFormIdOperationCompleted, userState);
        }
        
        private void OnGetFormStructureByFormIdOperationCompleted(object arg) {
            if ((this.GetFormStructureByFormIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFormStructureByFormIdCompleted(this, new GetFormStructureByFormIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.1st-excellence.com/GetTaskData", RequestNamespace="http://www.1st-excellence.com", ResponseNamespace="http://www.1st-excellence.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTaskData(string taskId) {
            object[] results = this.Invoke("GetTaskData", new object[] {
                        taskId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTaskDataAsync(string taskId) {
            this.GetTaskDataAsync(taskId, null);
        }
        
        /// <remarks/>
        public void GetTaskDataAsync(string taskId, object userState) {
            if ((this.GetTaskDataOperationCompleted == null)) {
                this.GetTaskDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTaskDataOperationCompleted);
            }
            this.InvokeAsync("GetTaskData", new object[] {
                        taskId}, this.GetTaskDataOperationCompleted, userState);
        }
        
        private void OnGetTaskDataOperationCompleted(object arg) {
            if ((this.GetTaskDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTaskDataCompleted(this, new GetTaskDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.1st-excellence.com/SetRelayFormData", RequestNamespace="http://www.1st-excellence.com", ResponseNamespace="http://www.1st-excellence.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetRelayFormData(string relayFormData) {
            object[] results = this.Invoke("SetRelayFormData", new object[] {
                        relayFormData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetRelayFormDataAsync(string relayFormData) {
            this.SetRelayFormDataAsync(relayFormData, null);
        }
        
        /// <remarks/>
        public void SetRelayFormDataAsync(string relayFormData, object userState) {
            if ((this.SetRelayFormDataOperationCompleted == null)) {
                this.SetRelayFormDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetRelayFormDataOperationCompleted);
            }
            this.InvokeAsync("SetRelayFormData", new object[] {
                        relayFormData}, this.SetRelayFormDataOperationCompleted, userState);
        }
        
        private void OnSetRelayFormDataOperationCompleted(object arg) {
            if ((this.SetRelayFormDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetRelayFormDataCompleted(this, new SetRelayFormDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.1st-excellence.com/TerminateTask", RequestNamespace="http://www.1st-excellence.com", ResponseNamespace="http://www.1st-excellence.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TerminateTask(string taskId, string account, string result, string reason) {
            object[] results = this.Invoke("TerminateTask", new object[] {
                        taskId,
                        account,
                        result,
                        reason});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TerminateTaskAsync(string taskId, string account, string result, string reason) {
            this.TerminateTaskAsync(taskId, account, result, reason, null);
        }
        
        /// <remarks/>
        public void TerminateTaskAsync(string taskId, string account, string result, string reason, object userState) {
            if ((this.TerminateTaskOperationCompleted == null)) {
                this.TerminateTaskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTerminateTaskOperationCompleted);
            }
            this.InvokeAsync("TerminateTask", new object[] {
                        taskId,
                        account,
                        result,
                        reason}, this.TerminateTaskOperationCompleted, userState);
        }
        
        private void OnTerminateTaskOperationCompleted(object arg) {
            if ((this.TerminateTaskCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TerminateTaskCompleted(this, new TerminateTaskCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.1st-excellence.com/GetTaskResult", RequestNamespace="http://www.1st-excellence.com", ResponseNamespace="http://www.1st-excellence.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTaskResult(string taskId, string isContainFormData) {
            object[] results = this.Invoke("GetTaskResult", new object[] {
                        taskId,
                        isContainFormData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTaskResultAsync(string taskId, string isContainFormData) {
            this.GetTaskResultAsync(taskId, isContainFormData, null);
        }
        
        /// <remarks/>
        public void GetTaskResultAsync(string taskId, string isContainFormData, object userState) {
            if ((this.GetTaskResultOperationCompleted == null)) {
                this.GetTaskResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTaskResultOperationCompleted);
            }
            this.InvokeAsync("GetTaskResult", new object[] {
                        taskId,
                        isContainFormData}, this.GetTaskResultOperationCompleted, userState);
        }
        
        private void OnGetTaskResultOperationCompleted(object arg) {
            if ((this.GetTaskResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTaskResultCompleted(this, new GetTaskResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SendFormCompletedEventHandler(object sender, SendFormCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendFormCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendFormCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetFormListCompletedEventHandler(object sender, GetFormListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFormListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFormListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetExternalFormListCompletedEventHandler(object sender, GetExternalFormListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetExternalFormListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetExternalFormListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetFormStructureCompletedEventHandler(object sender, GetFormStructureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFormStructureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFormStructureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetFormStructureByFormIdCompletedEventHandler(object sender, GetFormStructureByFormIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFormStructureByFormIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFormStructureByFormIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetTaskDataCompletedEventHandler(object sender, GetTaskDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTaskDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTaskDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SetRelayFormDataCompletedEventHandler(object sender, SetRelayFormDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetRelayFormDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetRelayFormDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void TerminateTaskCompletedEventHandler(object sender, TerminateTaskCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TerminateTaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TerminateTaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetTaskResultCompletedEventHandler(object sender, GetTaskResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTaskResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTaskResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591